### ISSUE TITLE
Avoid long tasks that block ad-related network requests (show_ads_impl_fy2019.js)

### ISSUE THREAD

**Issue by Bangkokian** [googleads/publisher-ads-lighthouse-plugin#189] opened 2020-03-12 05:59 UTC
I'm receiving the warning message to "Avoid long tasks that blog ad-related network requests -- 0.1 s blocked".

The warning message applies to the resource **show_ads_impl_fy2019.js**, which is part of **adsbygoogle.js**

In other words, a script which is required to show ads is being flagged itself as a "long task that blocks ad-related network requests."

**Comment by jimper** [comment] 2020-03-12 07:09
Could you share the URL of the page(s) you were testing and clarify how you were running the tool, so the team can take a closer look?

**Comment by Bangkokian** [comment] 2020-03-12 14:40
To run the tool, I'm just entering the page URL directly from: https://developers.google.com/publisher-ads-audits/

The page is at: https://www.ifate.com/i-ching.html

Btw -- the inclusion of Auto Ads' **adsbygoogle.js** on the page seems to be causing an additional issue as well:

- show_ads_impl_fy2019.js is being flagged as a long task which blocks ad-related networks requests. As noted previously, this script is part of adsbygoogle.js and is necessary to show ads.
- There is an additional warning to render ads using lazy loading -- but the ads listed are "aswift_1", "aswift_2", ... "aswift_6". These are dynamically generated placements created by Auto Ads. AFAIK there is no way to implement lazy loading for these, as advised.

**Comment by jonkeller** [comment] 2020-03-27 14:54
Hi - starting work on this now. I am able to reproduce both the original issue and the additional issue using the URL you provided. I'll post updates as they're available...

**Comment by jonkeller** [comment] 2020-03-27 18:18
Also, @Bangkokian: possibly unrelated to the current bug, but when I load https://www.ifate.com/runes.html I see ```<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>``` repeated 6 times.

**Comment by Bangkokian** [comment] 2020-03-27 19:43
Ah.. looks like snippets were just pasted in without removing the extra
script tags.

Corrected.

Thanks for the heads-up.

**Comment by jonkeller** [comment] 2020-03-30 15:47
Partially fixed with #193

**Comment by jonkeller** [comment] 2020-04-06 22:52
Great - thanks for removing the extra gpt.js inclusions. I do still see adsbygoogle.js included twice, though.
Breaking the issues down:
* “Avoid long tasks that block ad-related network requests” - this is a bug. Thanks for finding it! It is fixed in #193.
* “Ad request waterfall” - it is the case that adsbygoogle.js is being loaded after an ad request that comes from gpt.js. So I feel that the tool is working as intended. Just checking, is it intentional that you have both GPT and AdSense running on the same page? If so, that’s fine - I just want to verify this is intentional. If you indeed need both of them, it may help to move the inclusion of adsbygoogle.js to above all the googletag.cmd.push calls.
* “Avoid loading ads until they are nearly on-screen” - If using only GPT, enabling lazy loading as described in the audit should take care of things. I have created #194 to disable this audit for Adsense-only sites.

**Closed by jonkeller** 2020-04-06 22:52 UTC

**Comment by Bangkokian** [comment] 2020-04-07 07:46
> "Just checking, is it intentional that you have both GPT and AdSense
running on the same page? If so, that’s fine - I just want to verify this
is intentional. "

Yes, it's intentional, but it may not be the best setup?

It's my understanding that using both scripts is the only way to add Auto
Ads, to my Ad Manager setup.  (I use Ad Manager with an Adsense fallback
for unsold inventory. I don't see any way to add Auto Ads to that setup
without the additional script tag)

I'll try moving adsbygoogle.js as you suggested. Thanks!
